### ISSUE TITLE
Increase responsiveness of the website

### ISSUE THREAD

**Issue by GTgyani206** [CollaboraOnline/CollaboraOnline.github.io#108]
### Description 
I have noticed that the source code of the website uses px as the CSS unit. This might result in a less friendly user experience for smaller screen sizes. 

### Method to reproduce error

- First, open the website, then go to inspect option
- then choose responsiveness option and select any device

### Video of the bug
https://github.com/CollaboraOnline/CollaboraOnline.github.io/assets/128274569/7ea782e9-d7d0-4e1b-a305-29bccd79a0ac

### Expected behaviour 
the webpage should be fully visible 

### Current Behavior
The webpage is stretched out.

### Sugested fixes
We can use rem instead of px to increase responsiveness

**Comment by DevyanshuNegi** [comment]
can I work on this
