### ISSUE TITLE
Footer: Add dev.to icon

### ISSUE THREAD

**Issue by pedropintosilva** [CollaboraOnline/CollaboraOnline.github.io#25]
**This is an [Easy Hack](https://collaboraonline.github.io/post/easyhacks/).**
Potential mentors: @pedropintosilva 

### Detailed description and rationale
Currently we have a bunch of icon placed within the footer, dev.to `https://dev.to/collaboraonline` is missing there:
![image](https://user-images.githubusercontent.com/65948705/137103088-07fdfc89-fe23-4cbe-8ee1-597e76701ed9.png)

### Code pointers
1. Add dev.top to the `[params.social]` in the configuration file: https://github.com/CollaboraOnline/CollaboraOnline.github.io/blob/master/config.toml
2. Edit the respective partial (footer.html): https://github.com/CollaboraOnline/CollaboraOnline.github.io/blob/master/layouts/partials/footer.html
3. Don't forget to change the SVG in https://github.com/CollaboraOnline/CollaboraOnline.github.io/blob/master/layouts/partials/footer.html
  * Remember to make sure you add/adjust the svg line so these are present: ``aria-hidden="true" focusable="false" class="svg-inline--fa fa-comment-dots fa-w-16 fa-stack-1x fa-inverse" role="img"`

**Comment by samyaksand** [comment]
Please assign me this issue
